### ISSUE TITLE
Incorrect simplification of permutation polynomial

### ISSUE THREAD

**Issue by Colton1skees** [DenuvoSoftwareSolutions/GAMBA#2]
Given the permutation polynomial `(((x^y)*-3751285467811676160)+((((x*y)*(x*y))*7439751665915265024)+(((x|y)*(((x*y)*1392593702064488448)+(928395801376325632*(x|y))))+((((x^y)*-8527075185822531584)*(x*y))+(((x^y)*((928395801376325632*(x|y))+(-8991273086510694400*(x^y))))+(1567872932321951744+(((x*y)*-6507636315486420992)+(((x|y)*3620980961824473088)+(((x^y)*1810490480912236544)+((7357730074168131584+((((-928395801376325632*(x|y))*((x|y)+(x^y)))+(((x*y)*(((x^y)*8527075185822531584)+2911192480349159427))+((x^y)*((8991273086510694400*(x^y))+1940794986899439618))))+((x|y)*3881589973798879236)))+((x*y)*((-7439751665915265024*(x*y))+((x|y)*-1392593702064488448)))))))))))))`,

running GAMBA(with the arguments `-b 64`) incorrectly yields `8925603006490083328+x*(7502570935623352326-5453235437889912829*y+1856791602752651264*(x&y)+x*(6511355864538939392-7439751665915265024*y**2))+y*(7502570935623352326-928395801376325632*y+1856791602752651264*(x&y))+(-7502570935623352328-928395801376325632*(x&y))*(x&y)+928395801376325632*(x|y)**2`.

Here's a script to prove the inequivalence. Also note that I'm using the latest version of GAMBA. 
```
import z3

def prove_equivalent(expr1, expr2):
    solver : z3.Solver = z3.Solver()
    solver.add(z3.Not(expr1 == expr2))
    check : z3.CheckSatResult = solver.check()
    if check == z3.sat:
        print(f'Expressions are not equivalent: {check}\n{solver.model()}')
    elif check == z3.unsat:
        print(f'Expressions are equivalent: {check}')
    else:
        raise NotImplementedError()

def prove_with_evaluation():
    x = 3228536322291359743
    y = 8836635477638107370
    ast_before_gamba = (((x^y)*-3751285467811676160)+((((x*y)*(x*y))*7439751665915265024)+(((x|y)*(((x*y)*1392593702064488448)+(928395801376325632*(x|y))))+((((x^y)*-8527075185822531584)*(x*y))+(((x^y)*((928395801376325632*(x|y))+(-8991273086510694400*(x^y))))+(1567872932321951744+(((x*y)*-6507636315486420992)+(((x|y)*3620980961824473088)+(((x^y)*1810490480912236544)+((7357730074168131584+((((-928395801376325632*(x|y))*((x|y)+(x^y)))+(((x*y)*(((x^y)*8527075185822531584)+2911192480349159427))+((x^y)*((8991273086510694400*(x^y))+1940794986899439618))))+((x|y)*3881589973798879236)))+((x*y)*((-7439751665915265024*(x*y))+((x|y)*-1392593702064488448)))))))))))))
    ast_after_gamba = 8925603006490083328+x*(7502570935623352326-5453235437889912829*y+1856791602752651264*(x&y)+x*(6511355864538939392-7439751665915265024*y**2))+y*(7502570935623352326-928395801376325632*y+1856791602752651264*(x&y))+(-7502570935623352328-928395801376325632*(x&y))*(x&y)+928395801376325632*(x|y)**2
    # Wrap all operands in parenthesis to prove it's not an operator precedence issue.
    parenthesized_after_gamba = ((((8925603006490083328+(x*(((7502570935623352326+((5453235437889912829*y)*-1))+(1856791602752651264*(x&y)))+(x*(6511355864538939392+((7439751665915265024*(y**2))*-1))))))+(y*((7502570935623352326+((928395801376325632*y)*-1))+(1856791602752651264*(x&y)))))+(((7502570935623352328*-1)+((928395801376325632*(x&y))*-1))*(x&y)))+(928395801376325632*((x|y)**2)))

    print(f"before gamba: {ast_before_gamba % (2**64)}")
    print(f"after gamba: {ast_after_gamba % (2**64)}")
    print(f"after gamba(with the expression parenthesized): {parenthesized_after_gamba % (2 ** 64)}")
    return

x = z3.BitVec('x', 64);
y = z3.BitVec('y', 64);

# Input AST given to gamba
ast_before_gamba = (((x^y)*-3751285467811676160)+((((x*y)*(x*y))*7439751665915265024)+(((x|y)*(((x*y)*1392593702064488448)+(928395801376325632*(x|y))))+((((x^y)*-8527075185822531584)*(x*y))+(((x^y)*((928395801376325632*(x|y))+(-8991273086510694400*(x^y))))+(1567872932321951744+(((x*y)*-6507636315486420992)+(((x|y)*3620980961824473088)+(((x^y)*1810490480912236544)+((7357730074168131584+((((-928395801376325632*(x|y))*((x|y)+(x^y)))+(((x*y)*(((x^y)*8527075185822531584)+2911192480349159427))+((x^y)*((8991273086510694400*(x^y))+1940794986899439618))))+((x|y)*3881589973798879236)))+((x*y)*((-7439751665915265024*(x*y))+((x|y)*-1392593702064488448)))))))))))))

# Output AST from gamba:
# Note: (x|y)**2 has been replaced with ((x|y) * (x|y)),
# and y**2 has been replaced with (y*y).
ast_after_gamba = 8925603006490083328+x*(7502570935623352326-5453235437889912829*y+1856791602752651264*(x&y)+x*(6511355864538939392-7439751665915265024*(y*y)))+y*(7502570935623352326-928395801376325632*y+1856791602752651264*(x&y))+(-7502570935623352328-928395801376325632*(x&y))*(x&y)+928395801376325632*((x|y) * (x|y))

prove_with_evaluation()
prove_equivalent(ast_before_gamba, ast_after_gamba)
```

The ground truth of the expression is `8925603006490083328+2*(x^y)+7502570935623352324*(x|y)-3596443835137261565*x*y`.

**Comment by Colton1skees** [comment]
I tried to minimize the bug, but the example is as far as I can get it - the issue disappears if you remove the RHS(```(((x^y)*-3751285467811676160) + ```) of the tree.

Strangely the MBA expression is simplified down to it's ground truth with just this code:
```
root = parse(expression, 64, False)
root.refine()
root.expand(True)
```

**Comment by pmeerw** [comment]
thanks for reporting, small fix has been committed in function __is_candidate_for_simplification_in_sum()

**Comment by breichenwallner** [comment]
Please note that GAMBA finishes with a valid result now for the reported input, but that result still deviates from the expected ground truth. This is due to some desicion it makes during the process which simplifies the expression at that point on the one hand, but prevents GAMBA finding from even better simplifications later on on the other hand. This can happen for some inputs, we decided not go for any boosting of our algorithm in this concern.
